### ISSUE TITLE
GTM tag not firing (newest yourls release)

### ISSUE THREAD

**Issue by romualdasm** [dorks-delivered/GTM-for-YOURLS#2]
The gtm tag is NOT firing prior to redirect, newest yourls rel. version: 1.7.9

**CONFIG:**

<?php
/*
Plugin Name: GoogleTagManager for YOURLS
Plugin URI: https://github.com/dorks-delivered/GTM-for-YOURLS
Description: Adds google tag manager tracking to every clicked link
Version: 1
Author: Dorks Delivered
Author URI: https://dorks.com.au/
*/

if( !defined( 'YOURLS_ABSPATH' ) ) die();

yourls_add_action( 'pre_redirect', 'gtm_add_tracking' );

function gtm_add_tracking( $args ) {
    $url = $args[0];
    $code = $args[1];
    $tagid = "GTM-TXRX5CH"; // SET TAGID HERE

    echo "<html>";
    echo "<head>";
    echo "
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','$tagid');</script>
    ";
    echo "</head>";

    echo "<body>";
    echo "
    <noscript><iframe src=\"https://www.googletagmanager.com/ns.html?id=$tagid\"
    height=\"0\" width=\"0\" style=\"display:none;visibility:hidden\"></iframe></noscript>
    ";
    echo "<p>Please <a href='$url'>click here</a> if you are not automatically redirected.</p>";
    echo "</body>";
    echo "</html>";
}

**Comment by tannertechnology** [comment]
Thanks for submitting an issue,

I appear to have reproduced this and am working to solve it. I'll release an update or more info tomorrow probably.

**Comment by romualdasm** [comment]
Wow, Tanner - thank you very much, I really need your help.

Rom


*___________________*
*Romualdas Mačiulis*

**Comment by tannertechnology** [comment]
Hey Rom,

Turns out I'm having trouble reproducing this on a test instance. Tonight I'll update our production instance and test it as well. In the mean time would you mind uploading your entire plugin.php to a private gist and emailing it to tanner.anderson [at] dorks.com.au? Also, what environment are you hosting on? My test environment is on apache however our main instance is on CPanel.

Thanks!
~Tanner

**Comment by romualdasm** [comment]
*I am not a software developer, so not sure how...*

*including the code here:*







































*<?php/*Plugin Name: GoogleTagManager for YOURLSPlugin URI:
https://github.com/dorks-delivered/GTM-for-YOURLS
<https://github.com/dorks-delivered/GTM-for-YOURLS>Description: Adds google
tag manager tracking to every clicked linkVersion: 1Author: Dorks
DeliveredAuthor URI: https://dorks.com.au/ <https://dorks.com.au/>*/if(
!defined( 'YOURLS_ABSPATH' ) ) die();yourls_add_action( 'pre_redirect',
'gtm_add_tracking' );function gtm_add_tracking( $args ) {    $url =
$args[0];    $code = $args[1];    $tagid = "GTM-TXRX5CH"; // SET TAGID
HERE    echo "<html>";    echo "<head>";    echo "    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var
f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f)
<https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f)>;
  })(window,document,'script','dataLayer','$tagid');</script>    ";    echo "</head>";    echo "<body>";    echo "    <noscript><iframe
src=\"https://www.googletagmanager.com/ns.html?id=$tagid\
<https://www.googletagmanager.com/ns.html?id=$tagid\>"    height=\"0\"
width=\"0\" style=\"display:none;visibility:hidden\"></iframe></noscript>
  ";    echo "<p>Please <a
href='$url'>click here</a> if you are not automatically redirected.</p>";
  echo "</body>";    echo "</html>";}*

**Comment by tannertechnology** [comment]
Hey @romualdasm,

Sorry for the delay here. I have tested on a test instance pointing to YOURLS master branch (1.7.10) and our production instance on the latest stable release (1.7.9) and am unable to reproduce this issue. Would you mind emailing tanner.anderson [at] dorks.com.au so I can provide more specific support and I'll update this issue when we come to a resolution?

~Tanner

**Comment by tannertechnology** [comment]
We appear to have isolated the issue and are testing the resolution.
